import type { AiNodeType, NodeAttributeConfig } from '../model';

export const audioNodes = {
  voiceover: {
    label: '配音节点',
    category: '音频',
    kind: 'audio',
    accent: '#10b981',
    summary: '文本转语音，控制音色、语速、情绪和口播节奏。',
    tabs: ['文本', '音色', '情绪', '导出'],
    metrics: [['字数', '64'], ['语速', '0.9x'], ['音色', '男声'], ['时长', '8s']],
    fields: [['音色', '温和中年男声'], ['语速', '偏慢'], ['情绪', '克制、纪录片感'], ['响度', '-16 LUFS']],
    chips: ['纪录片', '低情绪', '无口播', '可对口型'],
    activeChips: [0, 1],
    sliders: [['语速', 44], ['情绪强度', 38], ['清晰度', 78]],
    actions: ['生成配音', '试听', '同步字幕'],
  },
  music: {
    label: '背景音乐',
    category: '音频',
    kind: 'audio',
    accent: '#34d399',
    summary: '生成或引用 BGM，控制情绪、节奏、时长和音量。',
    tabs: ['音乐', '情绪', '音量', '版权'],
    metrics: [['时长', '20s'], ['音量', '-24db'], ['情绪', '安静'], ['状态', '禁用']],
    fields: [['音乐策略', '全程无背景音乐'], ['替代方案', '保留自然环境声'], ['响度', '不高于人声'], ['版权', '项目内生成']],
    chips: ['无背景音乐', '环境声优先', '低音量', '淡入淡出'],
    activeChips: [0, 1],
    sliders: [['音乐音量', 0], ['环境融合', 35], ['情绪强度', 22]],
    actions: ['生成 BGM', '静音', '加入时间线'],
  },
  soundEffect: {
    label: '音效节点',
    category: '音频',
    kind: 'audio',
    accent: '#22c55e',
    summary: '生成脚步声、道具碰撞、环境声和转场音效。',
    tabs: ['音效', '时间点', '混音', '导出'],
    metrics: [['音效', '4'], ['同步', '帧级'], ['音量', '-18db'], ['状态', '待混']],
    fields: [['音效类型', '纸鸢展开、木桌轻响、脚步'], ['对齐方式', '绑定视频帧点'], ['空间感', '室内近距离'], ['混音', '低音量自然融合']],
    chips: ['脚步声', '纸张声', '木桌声', '室内混响'],
    activeChips: [1, 2, 3],
    sliders: [['音效音量', 42], ['同步精度', 88], ['混响强度', 36]],
    actions: ['生成音效', '自动对齐', '混入轨道'],
  },
  audioSeparation: {
    label: '音频分离',
    category: '音频',
    kind: 'audio',
    accent: '#14b8a6',
    summary: '从视频中拆分人声、音乐和环境声，支持静音或单独导出。',
    tabs: ['分离', '通道', '降噪', '导出'],
    metrics: [['人声', '82%'], ['环境', '48%'], ['音乐', '0%'], ['时长', '10s']],
    fields: [['分离模型', 'Vocal / Music / Ambience'], ['保留通道', '环境声'], ['静音策略', '移除背景音乐'], ['导出格式', 'WAV / AAC']],
    chips: ['人声分离', '音乐静音', '环境保留', '降噪'],
    activeChips: [1, 2, 3],
    sliders: [['降噪强度', 64], ['环境声保留', 35], ['人声清晰', 82]],
    actions: ['重新分离', '导出 WAV', '生成字幕'],
  },
  lipSync: {
    label: '对口型',
    category: '音频',
    kind: 'video',
    accent: '#0d9488',
    summary: '让角色口型匹配配音或导入音频，适合数字人和对白镜头。',
    tabs: ['音频', '人脸', '口型', '输出'],
    metrics: [['音频', '8s'], ['人脸', '1'], ['同步', '高'], ['强度', '72']],
    fields: [['驱动音频', '配音节点 01'], ['人脸来源', '视频首帧检测'], ['口型强度', '自然'], ['保护区域', '眼部和背景不动']],
    chips: ['自然口型', '保留表情', '人脸锁定', '静音替换'],
    activeChips: [0, 1, 2],
    sliders: [['口型强度', 72], ['表情保留', 61], ['背景保护', 86]],
    actions: ['生成口型', '校准音频', '导出结果'],
  },
} satisfies Pick<Record<AiNodeType, NodeAttributeConfig>, 'voiceover' | 'music' | 'soundEffect' | 'audioSeparation' | 'lipSync'>;
