import type { AiNodeType, NodeAttributeConfig } from '../model';

export const referenceNodes = {
  imageReference: {
    label: '图片参考',
    category: '参考控制',
    kind: 'image',
    accent: '#f6b84d',
    summary: '通用图片参考，可作为角色、场景、风格、道具的输入来源。',
    tabs: ['参考设置', '裁剪', '用途', '版本'],
    metrics: [['权重', '78'], ['绑定', '3'], ['相似', '高'], ['版本', 'v4']],
    fields: [['来源', '本地上传 / 资产库'], ['裁剪比例', '16:9'], ['默认用途', '全能参考'], ['下游节点', '3 个生成节点']],
    chips: ['角色外观', '服装道具', '场景光线', '构图比例'],
    activeChips: [0, 1],
    sliders: [['参考权重', 78], ['风格迁移', 52], ['细节保留', 70]],
    actions: ['设为角色', '生成视频', '抠像裁剪'],
  },
  characterReference: {
    label: '角色库',
    category: '参考控制',
    kind: 'image',
    accent: '#fb7185',
    summary: '维护同一角色的正侧背、服装、表情与动作参考。',
    tabs: ['角色', '姿态', '服装', '绑定'],
    metrics: [['图片', '8'], ['视频', '5'], ['一致性', '高'], ['锁定', '开']],
    fields: [['角色名', '孙子 / 爷爷'], ['参考视角', '正面、侧面、背面'], ['服装规则', '蓝色 T 恤、短裤'], ['禁用规则', '不出现正脸特写']],
    chips: ['身份锁定', '服装锁定', '年龄保持', '体态保持'],
    activeChips: [0, 1, 3],
    sliders: [['身份一致性', 92], ['姿态自由度', 48], ['服装保真', 86]],
    actions: ['绑定下游', '补充视角', '生成角色卡'],
  },
  sceneReference: {
    label: '场景参考',
    category: '参考控制',
    kind: 'image',
    accent: '#a3e635',
    summary: '固定空间结构、光线、时间、陈设和场景连续性。',
    tabs: ['空间', '光线', '陈设', '镜头'],
    metrics: [['场景', '老屋'], ['光线', '晨光'], ['节点', '6'], ['锁定', '中']],
    fields: [['空间结构', '老屋书房'], ['主光源', '清晨暖金色自然光'], ['关键陈设', '木桌、窗棂、民俗道具'], ['连续策略', '维持桌面方位']],
    chips: ['空间锁定', '自然光', '道具保持', '景深统一'],
    activeChips: [0, 1, 2],
    sliders: [['场景保真', 82], ['光线一致', 74], ['背景变化', 28]],
    actions: ['应用场景', '提取风格', '生成空镜'],
  },
  propReference: {
    label: '道具/产品参考',
    category: '参考控制',
    kind: 'image',
    accent: '#f97316',
    summary: '固定产品或道具外观，避免生成时形状、纹理、标识漂移。',
    tabs: ['道具', '细节', '遮罩', '绑定'],
    metrics: [['道具', '4'], ['细节', '高'], ['绑定', '5'], ['漂移', '低']],
    fields: [['道具类型', '布老虎 / 泥塑钟馗 / 纸鸢'], ['细节锁定', '纹样、颜色、轮廓'], ['摆放规则', '桌面近景优先'], ['出镜方式', '手部操作或静物展示']],
    chips: ['轮廓锁定', '纹理锁定', '颜色锁定', '局部特写'],
    activeChips: [0, 1, 2],
    sliders: [['道具保真', 89], ['局部权重', 66], ['背景融合', 58]],
    actions: ['设为道具', '局部重绘', '生成特写'],
  },
  styleReference: {
    label: '风格参考',
    category: '参考控制',
    kind: 'image',
    accent: '#c084fc',
    summary: '控制摄影、美术、色调、质感和整体审美方向。',
    tabs: ['摄影', '色调', '质感', '迁移'],
    metrics: [['风格', '电影'], ['强度', '64'], ['色温', '暖'], ['镜头', '50mm']],
    fields: [['摄影风格', '电影级写实'], ['镜头质感', 'Canon R5 50mm f1.8'], ['色彩策略', '暖金色自然光'], ['颗粒/锐化', '轻微胶片颗粒']],
    chips: ['电影写实', '暖色调', '浅景深', '自然光'],
    activeChips: [0, 1, 2, 3],
    sliders: [['风格强度', 64], ['色彩统一', 76], ['写实保真', 83]],
    actions: ['应用风格', '保存预设', '生成样片'],
  },
} satisfies Pick<Record<AiNodeType, NodeAttributeConfig>, 'imageReference' | 'characterReference' | 'sceneReference' | 'propReference' | 'styleReference'>;
